name: pauzr
description: A time saver app
version: 1.0.3+3

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^0.9.0
  carousel_pro: ^0.0.13
  intro_slider: ^1.1.9
  cupertino_icons: ^0.1.2
  curved_navigation_bar: ^0.1.26
  flutter_vector_icons: ^0.1.0
  waveprogressbar_flutter: ^0.1.2
  shared_preferences: ^0.5.2
  xs_progress_hud: ^1.0.2
  connectivity: any
  image_picker: ^0.6.0+1
  flip_card: ^0.2.1
  intl: ^0.15.8
  swipedetector: ^1.2.0
  flutter_local_notifications: any
  share: ^0.6.1+1
  dio: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/photo_eraser.png
    - assets/images/photo_pencil.png
    - assets/images/photo_ruler.png
    - assets/images/hello.png
    - assets/images/man.png
    - assets/images/woman.png
    - assets/images/splash.png
    - assets/images/quotes/APJ-Abdul-Kalam.jpg
    - assets/images/quotes/Swami-Vivekananda.jpg
    - assets/images/quotes/Jack-Ma.png
    - assets/images/quotes/Barack-Obama.jpg
    - assets/images/quotes/Steve-Job.jpg
    - assets/images/quotes/Elon-Musk.jpg
    - assets/images/quotes/Ratan-Tata.jpg
    - assets/images/quotes/Bruce-Lee.jpg
    - assets/images/quotes/Dalai-Lama.jpg
    - assets/images/quotes/Abraham-Lincoln.jpg
    - assets/images/quotes/Sachin-Tendulkar.jpg
    - assets/images/quotes/Bill-Gates.jpg
    - assets/images/quotes/Mother-Teresa.jpg
    - assets/images/quotes/Dwayne-Johnson.jpg

  fonts:
    - family: TitilliumWeb-Black
      fonts:
        - asset: assets/fonts/TitilliumWeb-Black.ttf

    - family: TitilliumWeb-Bold
      fonts:
        - asset: assets/fonts/TitilliumWeb-Bold.ttf

    - family: TitilliumWeb-BoldItalic
      fonts:
        - asset: assets/fonts/TitilliumWeb-BoldItalic.ttf

    - family: TitilliumWeb-ExtraLight
      fonts:
        - asset: assets/fonts/TitilliumWeb-ExtraLight.ttf

    - family: TitilliumWeb-ExtraLightItalic
      fonts:
        - asset: assets/fonts/TitilliumWeb-ExtraLightItalic.ttf

    - family: TitilliumWeb-Italic
      fonts:
        - asset: assets/fonts/TitilliumWeb-Italic.ttf

    - family: TitilliumWeb-Light
      fonts:
        - asset: assets/fonts/TitilliumWeb-Light.ttf

    - family: TitilliumWeb-LightItalic
      fonts:
        - asset: assets/fonts/TitilliumWeb-LightItalic.ttf

    - family: TitilliumWeb-Regular
      fonts:
        - asset: assets/fonts/TitilliumWeb-Regular.ttf

    - family: TitilliumWeb-SemiBold
      fonts:
        - asset: assets/fonts/TitilliumWeb-SemiBold.ttf

    - family: TitilliumWeb-SemiBoldItalic
      fonts:
        - asset: assets/fonts/TitilliumWeb-SemiBoldItalic.ttf

    - family: Digital7-Italic
      fonts:
        - asset: assets/fonts/Digital7-Italic.ttf

    - family: Digital7-Mono
      fonts:
        - asset: assets/fonts/Digital7-Mono.ttf

    - family: Digital7-MonoItalic
      fonts:
        - asset: assets/fonts/Digital7-MonoItalic.ttf

    - family: Digital7
      fonts:
        - asset: assets/fonts/Digital7.ttf
