name: pauzr
description: A time saver app
version: 1.0.24+24

environment:
  sdk: ">=2.2.2 <3.0.0"

dependency_overrides:
  flutter:
    sdk: flutter
  provider: ^2.0.1+1
  flutter_bloc: ^0.9.0
  carousel_pro: ^0.0.13
  intro_slider: ^1.1.9
  cupertino_icons: ^0.1.2
  curved_navigation_bar: ^0.2.20
  flutter_vector_icons: ^0.1.0
  shared_preferences: ^0.5.2
  xs_progress_hud: ^1.0.2
  connectivity: any
  image_picker: ^0.6.0+1
  image_cropper: ^1.0.2
  flip_card: ^0.2.1
  intl: ^0.15.8
  swipedetector: ^1.2.0
  flutter_local_notifications: any
  share: ^0.6.1+1
  dio: ^2.1.9
  contacts_service: ^0.2.6
  permission_handler: ^3.0.2
  screen: ^0.0.5
  cached_network_image: ^0.8.0
  url_launcher: ^5.0.3
  firebase_messaging: ^5.0.4
  countdown: ^0.1.0
  liquid_progress_indicator: ^0.3.1
  firebase_analytics: ^4.0.1
  firebase_admob: ^0.9.0+2
  package_info: ^0.4.0+6
  timeago: ^2.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/finish.png
    - assets/images/photo_eraser.png
    - assets/images/photo_pencil.png
    - assets/images/photo_ruler.png
    - assets/images/hello.png
    - assets/images/man.png
    - assets/images/woman.png
    - assets/images/screen.png
    - assets/images/icon.png
    - assets/images/loading.gif
    - assets/images/intro/1.png
    - assets/images/intro/2.png
    - assets/images/intro/3.png
    - assets/images/intro/4.png

  fonts:
    - family: TitilliumWeb-Black
      fonts:
        - asset: assets/fonts/TitilliumWeb-Black.ttf

    - family: TitilliumWeb-Bold
      fonts:
        - asset: assets/fonts/TitilliumWeb-Bold.ttf

    - family: TitilliumWeb-BoldItalic
      fonts:
        - asset: assets/fonts/TitilliumWeb-BoldItalic.ttf

    - family: TitilliumWeb-ExtraLight
      fonts:
        - asset: assets/fonts/TitilliumWeb-ExtraLight.ttf

    - family: TitilliumWeb-ExtraLightItalic
      fonts:
        - asset: assets/fonts/TitilliumWeb-ExtraLightItalic.ttf

    - family: TitilliumWeb-Italic
      fonts:
        - asset: assets/fonts/TitilliumWeb-Italic.ttf

    - family: TitilliumWeb-Light
      fonts:
        - asset: assets/fonts/TitilliumWeb-Light.ttf

    - family: TitilliumWeb-LightItalic
      fonts:
        - asset: assets/fonts/TitilliumWeb-LightItalic.ttf

    - family: TitilliumWeb-Regular
      fonts:
        - asset: assets/fonts/TitilliumWeb-Regular.ttf

    - family: TitilliumWeb-SemiBold
      fonts:
        - asset: assets/fonts/TitilliumWeb-SemiBold.ttf

    - family: TitilliumWeb-SemiBoldItalic
      fonts:
        - asset: assets/fonts/TitilliumWeb-SemiBoldItalic.ttf

    - family: Digital7-Italic
      fonts:
        - asset: assets/fonts/Digital7-Italic.ttf

    - family: Digital7-Mono
      fonts:
        - asset: assets/fonts/Digital7-Mono.ttf

    - family: Digital7-MonoItalic
      fonts:
        - asset: assets/fonts/Digital7-MonoItalic.ttf

    - family: Digital7
      fonts:
        - asset: assets/fonts/Digital7.ttf
